import { expect, it } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { EMOTIONS, outfitFor, type ImageRequest } from '@shared-roof/shared';
import { buildApp } from '../app';
import { openDb, Store } from '../db';
import { MockLlm } from '../llm/mock';
import { replayEvents } from '../game/replay';
import { MockImageBackend } from './mock';
import { expressionRequest, outfitPortraitRequest, portraitRequest } from './requests';

it('browses cached artwork without generating, saves character edits, and reuses edited expressions in conversations', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'roof-library-'));
  const store = new Store(openDb(':memory:'));
  const requests: ImageRequest[] = [];
  const mock = new MockImageBackend(dir);
  const image = { name: 'comfyui', health: async () => true, generate: async (r: ImageRequest) => { requests.push(r); return { ...await mock.generate(r), placeholder: false }; } };
  const { app, session, queue } = await buildApp({ llm: new MockLlm(), image, store, workflowHash: 'library', cacheDir: dir, assetsDir: null });
  const inject = (url: string, payload?: Record<string, unknown>) => app.inject({ method: payload ? 'POST' : 'GET', url, payload });
  const generate = async (kind: 'walk' | 'expression', emotion = 'neutral', occasion = 'daily', outfit?: string, customExpression?: string) => {
    for (let i = 0; i < 5; i++) {
      const response = await inject('/api/image/character/ren/artwork/generate', { kind, emotion, occasion, day: 0, outfit, customExpression });
      expect(response.statusCode).toBe(200);
      const result = response.json();
      const ready = await queue.settle(result.image.key);
      expect(ready).toMatchObject({ status: 'ready', placeholder: false });
      if (result.complete) return ready;
    }
    throw new Error('Artwork dependency chain did not finish');
  };
  try {
    expect((await inject('/api/image/library')).statusCode).toBe(404);
    await session.newGame({ seed: 21, moveInDay: false });
    for (const c of Object.values(session.state!.characters)) await queue.settle(queue.request(portraitRequest(c), 60).key);
    const count = requests.length;
    const before = structuredClone(session.state!);
    const library = (await inject('/api/image/library?day=0&occasion=daily')).json();
    expect(library.characters.map((c: { id: string }) => c.id).sort()).toEqual(session.view().characters.map(c => c.id).sort());
    expect(library.characters.find((c: { id: string }) => c.id === 'ren').expressions.map((e: { emotion: string }) => e.emotion)).toEqual(EMOTIONS);
    expect(requests).toHaveLength(count);
    const edit = { kind: 'walk', seed: 123, instructions: 'Keep the glasses visible' };
    expect((await inject('/api/image/character/ren/artwork', edit)).statusCode).toBe(200);
    const walk = await generate('walk');
    expect(requests.at(-1)).toMatchObject({ kind: 'sprite', seed: 123, reference: queue.localFile(portraitRequest(session.state!.characters.ren)) });
    expect(requests.at(-1)!.prompt).toContain(edit.instructions);
    expect((await inject('/api/image/library?day=0')).json().characters.find((c: { id: string }) => c.id === 'ren').walk.url).toBe(walk.url);
    const expressionEdit = { kind: 'expression', emotion: 'happy', seed: 456, instructions: 'Make the smile softer' };
    expect((await inject('/api/image/character/ren/artwork', expressionEdit)).statusCode).toBe(200);
    const happy = await generate('expression', 'happy', 'date');
    const c = session.state!.characters.ren;
  const face = requests.findLast(r => r.kind === 'portrait' && r.subjectKey.includes(':expression:v3:happy'))!;
    expect(face.seed).toBe(456);
    expect(face.prompt).toContain('Make the smile softer');
    expect(face.prompt).toContain('happy expression');
    expect(face.reference).toBe(queue.localFile(outfitPortraitRequest(c, outfitFor(c, 'date', 0), queue.localFile(portraitRequest(c)))));
    const countAfter = requests.length;
    const stand = await inject('/api/image/character/ren/stand?occasion=date&day=0&emotion=happy');
    expect(stand.json().url).toBe(happy.url);
    expect(requests).toHaveLength(countAfter);
    const neutral = await generate('expression', 'neutral', 'date');
    expect((await inject('/api/image/character/ren/stand?occasion=date&day=0&emotion=neutral')).json().url).toBe(neutral.url);
    expect((await inject('/api/image/library?day=0&occasion=date')).json().characters.find((c: { id: string }) => c.id === 'ren').expressions.find((e: { emotion: string }) => e.emotion === 'neutral').image.url).toBe(neutral.url);
    queue.lastFailure = Date.now();
    expect((await inject('/api/image/character/ren/stand?occasion=date&day=0&emotion=sad')).json()).toMatchObject({ url: neutral.url, emotion: 'neutral' });
    expect((await inject('/api/image/character/ren/stand?occasion=date&day=0&emotion=happy')).json()).toMatchObject({ url: happy.url, emotion: 'happy' });
    queue.lastFailure = 0;
    const customOutfit = 'black tuxedo, white dress shirt & bow tie';
    const custom = await generate('expression', 'happy', 'formal', customOutfit);
    const query = `occasion=formal&day=0&outfit=${encodeURIComponent(customOutfit)}`;
    expect((await inject(`/api/image/character/ren/stand?${query}&emotion=happy`)).json().url).toBe(custom.url);
    const customLibrary = (await inject(`/api/image/library?${query}`)).json().characters.find((c: { id: string }) => c.id === 'ren');
    expect(customLibrary.outfit).toBe(customOutfit);
    expect(customLibrary.expressions.find((e: { emotion: string }) => e.emotion === 'happy').image.url).toBe(custom.url);
    const customExpression = 'Eyes looking left, one eyebrow raised, lips pressed together';
    const described = await generate('expression', 'neutral', 'formal', customOutfit, customExpression);
    const describedFace = requests.findLast(r => r.kind === 'portrait' && r.subjectKey.includes(':custom:'))!;
    expect(describedFace.prompt).toContain(`this exact expression: ${customExpression}`);
    expect(describedFace.prompt).not.toContain('Make the smile softer');
    expect(describedFace.editRegion).toBe('face');
    const describedQuery = `${query}&customExpression=${encodeURIComponent(customExpression)}`;
    expect((await inject(`/api/image/character/ren/stand?${describedQuery}&emotion=neutral`)).json().url).toBe(described.url);
    expect((await inject(`/api/image/library?${describedQuery}`)).json().characters.find((c: { id: string }) => c.id === 'ren').expressions.find((e: { emotion: string }) => e.emotion === 'neutral').image.url).toBe(described.url);
    expect(described.url).not.toBe(neutral.url);
    expect((await inject('/api/image/character/ren/artwork/generate', { kind: 'expression', customExpression: 'x'.repeat(501) })).statusCode).toBe(400);
    expect((await inject('/api/image/character/ren/artwork/generate', { kind: 'expression', customExpression: '   ' })).statusCode).toBe(400);
    expect((await inject('/api/image/character/ren/artwork/generate', { kind: 'expression', occasion: 'formal', outfit: 'x'.repeat(301) })).statusCode).toBe(400);
    expect((await inject('/api/image/character/ren/artwork/generate', { kind: 'expression', outfit: '   ' })).statusCode).toBe(400);
    expect(expressionRequest(c, 'sad').seed).toBe(c.portraitSeed);
    expect(session.state!.world).toEqual(before.world);
    expect(session.state!.rngState).toBe(before.rngState);
    expect(session.state!.characters.mio).toEqual(before.characters.mio);
    expect(replayEvents(store.events(session.state!.gameId))).toEqual(session.state);
    const save = session.save(1, 'artwork');
    session.load(save);
    expect(session.state!.characters.ren).toMatchObject({ spriteSeed: 123, spriteInstructions: edit.instructions, expressionEdits: { happy: { seed: 456, instructions: expressionEdit.instructions } } });
    for (const invalid of [{ ...expressionEdit, emotion: 'invented' }, { ...expressionEdit, emotion: 'neutral' }, { ...edit, instructions: 'x'.repeat(501) }]) expect((await inject('/api/image/character/ren/artwork', invalid)).statusCode).toBe(400);
    expect((await inject('/api/image/character/missing/artwork', edit)).statusCode).toBe(404);
  } finally {
    await app.close(); store.db.close(); rmSync(dir, { recursive: true, force: true });
  }
});
