import { expect, test } from '@playwright/test';

test('visual novel artwork targets the selected character, previews expressions and retains scene outfits', async ({ page, request }, info) => {
  await page.addInitScript(() => localStorage.setItem('shared-roof-settings', JSON.stringify({ typewriter: false, reducedMotion: true, sound: false })));
  const game = (await (await request.post('/api/game/new', { data: { seed: 21, moveInDay: false } })).json()).view;
  const name = (id: string) => game.characters.find((c: { id: string }) => c.id === id).name;
  const figureUrl = (id: string, emotion: string, occasion: string, outfit?: string, customExpression?: string) => `/assets/portraits/finished-${id}-knees-up-v3.png?face=${emotion}&outfit=${occasion}${outfit ? `&custom=${encodeURIComponent(outfit)}` : ''}${customExpression ? `&expression=${encodeURIComponent(customExpression)}` : ''}`;
  const generated: { id: string; emotion: string; occasion: string; outfit?: string; customExpression?: string }[] = [];
  let turn = 0;
  let offline = false;
  await page.route('**/api/image/character/*/stand?*', route => {
    const url = new URL(route.request().url());
    const id = url.pathname.split('/')[4];
    return route.fulfill({ json: { key: route.request().url(), status: 'ready', url: figureUrl(id, url.searchParams.get('emotion')!, url.searchParams.get('occasion')!, url.searchParams.get('outfit') ?? undefined, url.searchParams.get('customExpression') ?? undefined) } });
  });
  await page.route('**/api/image/character/*/artwork/generate', route => {
    const id = new URL(route.request().url()).pathname.split('/')[4];
    const { emotion, occasion, outfit, customExpression } = route.request().postDataJSON();
    generated.push({ id, emotion, occasion, ...(outfit ? { outfit } : {}), ...(customExpression ? { customExpression } : {}) });
    return route.fulfill({ json: { complete: true, image: { key: `generated-${generated.length}`, status: 'ready', placeholder: offline, url: figureUrl(id, emotion, occasion, outfit, customExpression) } } });
  });
  await page.route('**/api/scene/*/choose', route => route.fulfill({ json: { ok: true } }));
  await page.route('**/api/scene/*/stream', route => {
    const event = (name: string, data: unknown) => `event: ${name}\ndata: ${JSON.stringify(data)}\n\n`;
    const index = turn++ * 2;
    const body = event('scene', { title: 'Group conversation', premise: 'A shared breakfast.', location: 'kitchen', locationName: 'kitchen', occasion: 'daily', participants: ['ren', 'mio', game.playerId].map(id => ({ id, name: name(id) })), outsiders: [], isPlayerScene: true, eavesdrop: false, chat: false, intro: null, background: { key: '', status: 'failed' } }) +
      ['ren', 'mio'].map((id, i) => event('line-start', { index: index + i, speaker: id, name: name(id), caption: null, emotion: index ? 'neutral' : i ? 'shy' : 'happy' }) + event('line-end', { index: index + i, speaker: id, text: 'Let us make breakfast.', caption: null, source: 'mock' })).join('') +
      event('choice', { intents: ['joke'], recipients: ['ren', 'mio'].map(id => ({ id, name: name(id) })), canType: true, canEnd: true }) + event('end', {});
    return route.fulfill({ contentType: 'text/event-stream', body });
  });
  await page.goto('/');
  await page.getByRole('button', { name: /continue · episode 1/ }).click();
  await page.getByRole('button', { name: 'begin', exact: true }).click();
  await page.getByRole('button', { name: 'talk to Kai', exact: true }).click();
  await page.getByRole('dialog', { name: 'talk to Kai?' }).getByRole('button', { name: 'yes', exact: true }).click();
  const stage = page.getByRole('group', { name: 'people in this conversation' });
  const ren = stage.getByRole('img', { name: new RegExp(name('ren')) }).and(stage.locator('img'));
  const mio = stage.getByRole('img', { name: new RegExp(name('mio')) }).and(stage.locator('img'));
  await expect(stage.locator(':scope > div > img')).toHaveCount(2);
  await page.getByRole('button', { name: 'character artwork', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'generate character artwork' });
  await expect(dialog.getByRole('combobox', { name: 'character', exact: true }).locator('option')).toHaveCount(2);
  await dialog.getByRole('combobox', { name: 'character', exact: true }).selectOption('ren');
  await dialog.getByRole('combobox', { name: 'outfit', exact: true }).selectOption('beach');
  expect(generated).toHaveLength(0);
  await dialog.getByRole('textbox', { name: 'custom expression (optional)' }).fill('An expression that clothing-only must ignore');
  await dialog.getByRole('button', { name: 'generate clothing', exact: true }).click();
  await expect(dialog.getByRole('status')).toContainText(`${name('ren')}'s outfit is ready`);
  await expect(ren).toHaveAttribute('src', figureUrl('ren', 'neutral', 'beach'));
  await expect(mio).toHaveAttribute('src', figureUrl('mio', 'shy', 'daily'));
  expect(generated[0]).toEqual({ id: 'ren', emotion: 'neutral', occasion: 'beach' });
  await dialog.getByRole('combobox', { name: 'character', exact: true }).selectOption('mio');
  await dialog.getByRole('combobox', { name: 'expression', exact: true }).selectOption('excited');
  const customExpression = 'One eyebrow raised, eyes looking left, a restrained smile';
  await dialog.getByRole('textbox', { name: 'custom expression (optional)' }).fill(customExpression);
  await dialog.getByRole('combobox', { name: 'outfit', exact: true }).selectOption('beach');
  await dialog.getByRole('textbox', { name: 'custom outfit (optional)' }).fill('A clothing draft that expression-only must ignore');
  await dialog.getByRole('button', { name: 'generate expression', exact: true }).click();
  await expect(dialog.getByRole('status')).toContainText(`${name('mio')}'s expression is ready`);
  await expect(mio).toHaveAttribute('src', figureUrl('mio', 'excited', 'daily', undefined, customExpression));
  expect(generated[1]).toEqual({ id: 'mio', emotion: 'excited', occasion: 'daily', customExpression });
  const customOutfit = 'navy tailored pantsuit & white blouse';
  await dialog.getByRole('combobox', { name: 'outfit', exact: true }).selectOption('formal');
  await dialog.getByRole('textbox', { name: 'custom outfit (optional)', exact: true }).fill(customOutfit);
  await dialog.getByRole('button', { name: 'generate both', exact: true }).click();
  await expect(dialog.getByRole('status')).toContainText(`${name('mio')}'s clothing and expression are ready`);
  expect(generated[2]).toEqual({ id: 'mio', emotion: 'excited', occasion: 'formal', outfit: customOutfit, customExpression });
  await expect(mio).toHaveAttribute('src', figureUrl('mio', 'excited', 'formal', customOutfit, customExpression));
  await expect(ren).toHaveAttribute('src', figureUrl('ren', 'neutral', 'beach'));
  await dialog.getByRole('button', { name: 'generate expression', exact: true }).focus();
  await page.keyboard.press('p');
  await page.keyboard.press('1');
  await expect(dialog).toBeVisible();
  expect(turn).toBe(1);
  await page.screenshot({ path: info.outputPath('scene-artwork-controls.png') });
  await dialog.getByRole('button', { name: 'close', exact: true }).click();
  await page.getByRole('button', { name: '1. make a joke', exact: true }).click();
  await expect(mio).toHaveAttribute('src', figureUrl('mio', 'neutral', 'formal', customOutfit));
  await expect(ren).toHaveAttribute('src', figureUrl('ren', 'neutral', 'beach'));
  expect(generated).toHaveLength(3);
  await page.getByRole('button', { name: 'character artwork', exact: true }).click();
  offline = true;
  await dialog.getByRole('combobox', { name: 'character', exact: true }).selectOption('mio');
  await dialog.getByRole('combobox', { name: 'expression', exact: true }).selectOption('happy');
  await dialog.getByRole('button', { name: 'generate expression', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('Images are offline');
  await expect(mio).toHaveAttribute('src', figureUrl('mio', 'neutral', 'formal', customOutfit));
  offline = false;
  await dialog.getByRole('button', { name: 'generate expression', exact: true }).click();
  await expect(mio).toHaveAttribute('src', figureUrl('mio', 'happy', 'formal', customOutfit));
});
